import Head from 'next/head'

import Navbar from './components/Navbar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
      </Head>
      <body>

        <Navbar />
        <style jsx global>{`
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        li {
          list-style-type: none;
        }

        a {
          text-decoration: none;
        }
        
        body {
          overflow-x: hidden;
        }
      `}</style>
      </body>
    </>
  )
}
