import Head from 'next/head'

import Navbar from './components/Navbar'
import HeroSection from './components/HeroSection'
import CoinsList from './components/CoinList'

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Coin Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet" />
      </Head>
      <body>

        <Navbar />
        <HeroSection />
        <CoinsList data={data} />
        <style jsx global>{`
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
          font-family: 'Poppins', sans-serif;
        }
        li {
          list-style-type: none;
        }

        a {
          text-decoration: none;
        }
        
        body {
          overflow-x: hidden;
          background-color: white;
        }
      `}</style>
      </body>
    </>
  )
}


export async function getServerSideProps() {
  const res = await fetch(`https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false
  `)
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      data
    }
  }
}